DROP TABLE IF EXISTS SEGNALAZIONI_NUOVE_ACCOGLIENZE CASCADE;
DROP TABLE IF EXISTS TRASPORTI CASCADE;
DROP TABLE IF EXISTS RICHIESTE_ADOZIONI CASCADE;
DROP TABLE IF EXISTS FOTO CASCADE;
DROP TABLE IF EXISTS ANIMALI CASCADE;
DROP TABLE IF EXISTS ORGANIZZAZIONE CASCADE;
DROP TABLE IF EXISTS EVENTI CASCADE;
DROP TABLE IF EXISTS AMMINISTRATORI CASCADE;
DROP TABLE IF EXISTS UTENTI CASCADE;

CREATE TABLE UTENTI (
    Email VARCHAR(255) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cognome VARCHAR(100) NOT NULL,
    UtentePW VARCHAR(100) NOT NULL,
    Telefono VARCHAR(20),
    Via VARCHAR(255),
    Citta VARCHAR(100),
    CAP VARCHAR(5),

    CHECK (
        (Via IS NULL AND Citta IS NULL AND CAP IS NULL)
        OR
        (Via IS NOT NULL AND Citta IS NOT NULL AND CAP IS NOT NULL)
    )
);

CREATE TABLE AMMINISTRATORI (
    Email VARCHAR(255) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Cognome VARCHAR(100) NOT NULL,
    AdminPW VARCHAR(100) NOT NULL
);

CREATE TABLE EVENTI (
    Titolo VARCHAR(255) NOT NULL,
    DataPubblicazione DATE NOT NULL,
    DataEvento DATE CHECK (DataEvento >= DataPubblicazione) NOT NULL,
    DescrEvento TEXT NOT NULL,
    Img VARCHAR(512) NOT NULL,
    PRIMARY KEY (Titolo, DataEvento)
);

CREATE TABLE ORGANIZZAZIONE(
    Titolo VARCHAR(255) NOT NULL,
    DataEvento DATE NOT NULL,
    Email VARCHAR(255) NOT NULL,
    
    PRIMARY KEY (Titolo, DataEvento, Email),
    
    FOREIGN KEY (Titolo, DataEvento) REFERENCES EVENTI (Titolo, DataEvento) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (Email) REFERENCES AMMINISTRATORI (Email) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ANIMALI(
    IDanimale INT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    DataNascita DATE NOT NULL,
    DataRegistrazione DATE CHECK (DataRegistrazione >= DataNascita) NOT NULL,
    Sesso CHAR(1) NOT NULL,
    Tipo VARCHAR(5) NOT NULL,
    Colore VARCHAR(100) NOT NULL,
    Pelo VARCHAR(20) NOT NULL,
    Taglia VARCHAR(10) NOT NULL,
    Razza VARCHAR(100) NOT NULL,
    DescrFamiglia TEXT NOT NULL,
    DescrComportamentale TEXT NOT NULL,
    CondizioniMediche TEXT,
    Trasporto BOOLEAN NOT NULL,
    Email VARCHAR(255),

    FOREIGN KEY (Email) REFERENCES AMMINISTRATORI (Email) ON DELETE SET NULL ON UPDATE CASCADE,

    CHECK (Sesso IN ('F','M')),
    CHECK (Tipo IN ('Gatto','Cane')),
    CHECK ((Pelo IN ('Corto','Medio','Lungo')) OR (Pelo = 'Senza pelo' AND Tipo = 'Gatto')),
    CHECK (Taglia IN ('Piccolo','Medio','Grande'))  
);

CREATE TABLE FOTO(
    Path VARCHAR(512) PRIMARY KEY,
    IDanimale INT NOT NULL,
    FOREIGN KEY (IDanimale) REFERENCES ANIMALI (IDanimale) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PREFERITI(
	Email VARCHAR(255) NOT NULL,
	IDanimale INT NOT NULL,
	FOREIGN KEY (Email) REFERENCES UTENTI (Email) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (IDanimale) REFERENCES ANIMALI (IDanimale) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RICHIESTE_ADOZIONI(
    Email VARCHAR(255) NOT NULL,
    IDanimale INT NOT NULL,
    Trasporto BOOLEAN NOT NULL,
    Appunti TEXT,
    LetteraPresentazione TEXT NOT NULL,
    Stato VARCHAR(20) NOT NULL, 
    DataRichiesta DATE NOT NULL,
    DataFineValutazione DATE,
    DataInizioValutazione DATE,

    CHECK (DataFineValutazione >= DataRichiesta),
    CHECK (DataFineValutazione >= DataInizioValutazione),
    CHECK (Stato IN ('Nuova', 'In valutazione','Da trasportare','Conclusa', 'Respinta')),

    PRIMARY KEY(Email, IDanimale),
    FOREIGN KEY (Email) REFERENCES UTENTI (Email) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (IDanimale) REFERENCES ANIMALI (IDanimale) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TRASPORTI(
	ID INT PRIMARY KEY, 
    Email VARCHAR(255) NOT NULL,
    IDanimale INT NOT NULL,
    Via VARCHAR(255) NOT NULL,
    Citta VARCHAR(100) NOT NULL,
    CAP VARCHAR(5) NOT NULL,
    DataArrivo DATE NOT NULL,
    DataPartenza DATE NOT NULL,
    CHECK (DataArrivo >= DataPartenza),
    FOREIGN KEY (Email, IDanimale) REFERENCES RICHIESTE_ADOZIONI (Email, IDanimale) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE SEGNALAZIONI_NUOVE_ACCOGLIENZE (
    ID INT PRIMARY KEY, 
    EmailAmm VARCHAR(255),
    EmailRichiedente VARCHAR(255) NOT NULL,
    
    FOREIGN KEY (EmailAmm) REFERENCES AMMINISTRATORI (Email) ON DELETE SET NULL ON UPDATE CASCADE
);